### ISSUE TITLE
Getting error while using this component.

### ISSUE THREAD

**Issue by meghagupta12** [PredixDev/px-widths-responsive-design#2]
Hi,

I am using this component in my web application.
I am successfully able to install it via command:
bower install px-widths-responsive-design --save-dev

Now, I am running the application on gulp.
When I give gulp command, I see the following error:

![image](https://user-images.githubusercontent.com/29881245/29411160-3ea265fe-8371-11e7-8006-93281b9b447e.png)

Can u pls help me here .. 

Best Regards

**Comment by randyaskin** [comment]
This likely indicates that your project has an outdated or mismatched version of px-colors-design - refer to the bower version tool [here](https://www.predix-ui.com/#/tools/version-finder/) to figure out which versions of the components you should be using. `bower install` will always pull the latest version, by default, but you can specify an earlier version in your bower.json if you need to maintain your application in the pre-design-refresh configuration for the time being.

**Comment by randyaskin** [comment]
Sidenote: if you do need to go back to an earlier version, make sure you `rm -rf <path-to-your>bower_components` before re-installing everything to clear out the later version.

**Comment by meghagupta12** [comment]
Thanks Randyaskin for your reply

after deleting the older version of px-colors-design  and then installed 
newer version of px-colors-design by using bower install then run the gulp command then getting below error .

![image](https://user-images.githubusercontent.com/29881245/29444152-e74ae90e-83fa-11e7-9237-30115a53c97b.png)

can you please help me for this.

**Comment by randyaskin** [comment]
$graybg is a variable only used within the seed / webapp-starter, which has not yet been updated to use the design refresh versions of everything. I'm working with that team to update to the latest Predix UI components, but in the meantime you may need to stick to the pre-refresh versions indicated in the bower tool I linked before.

**Comment by meghagupta12** [comment]
That means should i use previous version of px-colors-design or something else 

could you please tell me here

**Comment by randyaskin** [comment]
Yes. If you continue to use the webapp-starter then you should use the versions from the black pre-refresh column as opposed to the red post-refresh column, for now.

**Comment by meghagupta12** [comment]
after removing of px-colors-design , i made the entry manually in bower.json  of "px-colors-design": "^0.3.0" then run bower install then choose 3 option for version as attached snapshot but still below error is coming .

![image](https://user-images.githubusercontent.com/29881245/29445072-155d375a-8402-11e7-92ce-c2b791dcc6af.png)

**Comment by randyaskin** [comment]
Just post your full list of dependencies from bower.json and I will help you with the versions that you need to resolve cleanly

**Comment by meghagupta12** [comment]
Here below are the dependencies which is defined in bower.json.


{
  "name": "predix-webapp-starter",
  "version": "^3.1.0",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "public/bower_components",
    "test",
    "sass",
    "tutorials"
  ],
  "dependencies": {
    "hopscotch": "^0.2.6",
    "polymer": "^1.6.1",
    "px-view": "^1.1.1",
    "app-route": "PolymerElements/app-route#^0.9.1",
    "px": "^1.4.3",
    "px-card": "^0.6.1",
    "px-layout-design": "^0.4.3",
    "px-starter-kit-design": "^0.7.0",
    "px-theme": "^2.0.0",
    "px-view-header": "^0.2.0",
    "px-path-guide": "^0.0.2",
    "px-login": "^1.0.0",
    "px-context-browser": "^1.6.7",
    "iron-ajax": "^1.4.3",
    "px-data-table": "^2.1.3",
    "es6-promise": "~3.3.1",
    "moment": "^2.17.1",
    "px-rangepicker": "~1.3.10",
    "px-dropdown": "^3.1.1",
    "px-widths-responsive-design": "^0.4.4",
    "px-vis-timeseries": "^1.0.0",
    "px-app-nav": "^1.10.9",
    "px-spacing-design": "^0.4.4",
    "px-buttons-design": "^1.1.7",
    "marked-element": "^1.3.1",
    "px-dark-theme": "^1.0.10",
    "px-simple-bar-chart": "^1.9.1"
  },
  "resolutions": {
    "px-datetime-common": "^0.7.0",
    "app-localize-behavior": "^0.10.2",
    "iron-ajax": "^2.0.0"
  }
}

**Comment by randyaskin** [comment]
Use this:
```
{
  "name": "predix-webapp-starter",
  "version": "^3.1.0",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "public/bower_components",
    "test",
    "sass",
    "tutorials"
  ],
  "dependencies": {
    "hopscotch": "^0.2.6",
    "polymer": "^1.6.0",
    "px-view": "^1.1.1",
    "app-route": "PolymerElements/app-route#^0.9.1",
    "px": "^1.4.3",
    "px-card": "^0.7.0",
    "px-theme": "^2.0.0",
    "px-view-header": "^0.2.0",
    "px-login": "^1.0.0",
    "px-context-browser": "^1.8.0",
    "iron-ajax": "^1.4.3",
    "px-data-table": "^2.1.3",
    "es6-promise": "~3.3.1",
    "moment": "^2.17.1",
    "px-rangepicker": "^1.4.0",
    "px-dropdown": "^3.1.0",
    "px-vis-timeseries": "^1.0.0",
    "px-app-nav": "^1.10.0",
    "marked-element": "^1.3.1",
    "px-dark-theme": "^1.0.0",
    "px-simple-bar-chart": "^1.9.0"
  },
  "devDependencies": {
    "px-spacing-design": "^0.4.0",
    "px-buttons-design": "^1.1.0",
    "px-layout-design": "^0.4.0",
    "px-starter-kit-design": "^0.7.0",
    "px-widths-responsive-design": "^0.4.0"
  },
  "resolutions": {
    "app-localize-behavior": "^1.0.0"
  }
}
```

Make sure you run `rm -rf public/bower_components` and then `bower install`. This set of dependencies will install cleanly and your sass will compile. If you add any more components, make sure you use the version in the *black* pre-refresh column from [this list](https://www.predix-ui.com/#/tools/version-finder), e.g. if you wanted to add progress-bar, you would use `bower install --save px-progress-bar#0.2.0`
